export const DEFAULT_COLLECTION_LIMIT = 25;
export const DEFAULT_ACTIVITY_LIMIT = 10;
export const DEFAULT_UPCOMING_LIMIT = 10;
export const DEFAULT_INITIAL_SYNC_BATCH_SIZE = 100;
export const MAX_INITIAL_SYNC_BATCH_SIZE = 1000;
