apiVersion: v1
kind: ConfigMap
metadata:
  name: applywise-config
  namespace: applywise
  labels:
    app: applywise-api
data:
  NODE_ENV: "production"
  PORT: "3000"
  REDIS_HOST: "redis-service"
  REDIS_PORT: "6379"
  REDIS_DB: "0"
  AWS_REGION: "us-east-1"
  POSTGRES_DB: "applywise"
  POSTGRES_USER: "applywise"
  MINIO_BUCKET: "applywise-resumes"
  LOG_LEVEL: "info"
