apiVersion: v1
kind: Service
metadata:
  name: applywise-api
  namespace: applywise
  labels:
    app: applywise-api
spec:
  type: ClusterIP
  selector:
    app: applywise-api
  ports:
    - name: http
      port: 80
      targetPort: 3000
      protocol: TCP
