-- ============================================================
-- Career Terminal — PostgreSQL Row-Level Security (RLS) Policies
-- ============================================================
--
-- Enables ROW LEVEL SECURITY on all user-owned tables and installs the
-- tenant-scoping policies. This is defense-in-depth: application-level
-- authorization remains the primary defense.
--
-- Identity model:
--   The request-scoped user id lives in the GUC `app.current_user_id`, set by
--   set_app_user_id() / set_app_user_id_session() (defined in the
--   20260731000001_add_database_roles migration). current_app_user_id()
--   returns the active user id (or NULL).
--
-- Policy semantics:
--   - A row is visible/modifiable when its user_id matches current_app_user_id()
--     OR the caller is a member of app_admin (system/ops access).
--   - Tables without a direct user_id column are scoped via a parent join.
--   - idempotency_records is a global table: any app role may access it.
--
-- The policy column names below match the table columns generated by the
-- baseline 0_init migration (snake_case via @@map).
-- ============================================================

-- ── 1. Enable RLS on user-owned tables ───────────────────────

ALTER TABLE "users" ENABLE ROW LEVEL SECURITY;

ALTER TABLE "candidate_profiles" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "user_id_mapping" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "user_email_connections" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "gmail_sync_states" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "gmail_checkpoints" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "sync_operations" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "sync_jobs" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "sync_batches" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "batch_email_jobs" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "dead_letter_emails" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "gmail_sync_queue" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "malware_scan_results" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "user_resumes" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "resumes" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "fact_observations" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "snapshots" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "extraction_runs" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "fact_provenance" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "canonical_candidate_intelligence" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "outcome_events" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "action_events" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "predictions" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "prediction_feedback" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "recommendations" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "events" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "job_applications" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "application_timeline_events" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "application_sources" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "application_status_history" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "email_messages" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "email_attachments" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "idempotency_records" ENABLE ROW LEVEL SECURITY;

-- ── 2. Policies ──────────────────────────────────────────────

CREATE POLICY users_owner_policy ON "users"
  FOR ALL
  USING ("id" = current_app_user_id() OR pg_has_role(current_user, 'app_admin', 'member'));

CREATE POLICY candidate_profiles_owner_policy ON "candidate_profiles"
  FOR ALL
  USING ("user_id" = current_app_user_id() OR pg_has_role(current_user, 'app_admin', 'member'));

CREATE POLICY user_id_mapping_owner_policy ON "user_id_mapping"
  FOR ALL
  USING ("user_id" = current_app_user_id() OR pg_has_role(current_user, 'app_admin', 'member'));

CREATE POLICY user_email_connections_owner_policy ON "user_email_connections"
  FOR ALL
  USING ("user_id" = current_app_user_id() OR pg_has_role(current_user, 'app_admin', 'member'));

CREATE POLICY gmail_sync_states_owner_policy ON "gmail_sync_states"
  FOR ALL
  USING ("user_id" = current_app_user_id() OR pg_has_role(current_user, 'app_admin', 'member'));

CREATE POLICY gmail_checkpoints_owner_policy ON "gmail_checkpoints"
  FOR ALL
  USING ("user_id" = current_app_user_id() OR pg_has_role(current_user, 'app_admin', 'member'));

CREATE POLICY sync_operations_owner_policy ON "sync_operations"
  FOR ALL
  USING ("user_id" = current_app_user_id() OR pg_has_role(current_user, 'app_admin', 'member'));

CREATE POLICY sync_jobs_owner_policy ON "sync_jobs"
  FOR ALL
  USING ("user_id" = current_app_user_id() OR pg_has_role(current_user, 'app_admin', 'member'));

CREATE POLICY sync_batches_owner_policy ON "sync_batches"
  FOR ALL
  USING ("user_id" = current_app_user_id() OR pg_has_role(current_user, 'app_admin', 'member'));

CREATE POLICY batch_email_jobs_owner_policy ON "batch_email_jobs"
  FOR ALL
  USING (
    EXISTS (
      SELECT 1 FROM "sync_batches" sb
      WHERE sb."id" = "batch_email_jobs"."batch_id"
        AND sb."user_id" = current_app_user_id()
    )
    OR pg_has_role(current_user, 'app_admin', 'member')
  );

CREATE POLICY dead_letter_emails_owner_policy ON "dead_letter_emails"
  FOR ALL
  USING ("user_id" = current_app_user_id() OR pg_has_role(current_user, 'app_admin', 'member'));

CREATE POLICY gmail_sync_queue_owner_policy ON "gmail_sync_queue"
  FOR ALL
  USING ("user_id" = current_app_user_id() OR pg_has_role(current_user, 'app_admin', 'member'));

CREATE POLICY malware_scan_results_owner_policy ON "malware_scan_results"
  FOR ALL
  USING ("user_id" = current_app_user_id() OR pg_has_role(current_user, 'app_admin', 'member'));

CREATE POLICY user_resumes_owner_policy ON "user_resumes"
  FOR ALL
  USING ("user_id" = current_app_user_id() OR pg_has_role(current_user, 'app_admin', 'member'));

CREATE POLICY resumes_owner_policy ON "resumes"
  FOR ALL
  USING ("user_id" = current_app_user_id() OR pg_has_role(current_user, 'app_admin', 'member'));

CREATE POLICY fact_observations_owner_policy ON "fact_observations"
  FOR ALL
  USING ("user_id" = current_app_user_id() OR pg_has_role(current_user, 'app_admin', 'member'));

CREATE POLICY snapshots_owner_policy ON "snapshots"
  FOR ALL
  USING ("user_id" = current_app_user_id() OR pg_has_role(current_user, 'app_admin', 'member'));

CREATE POLICY extraction_runs_owner_policy ON "extraction_runs"
  FOR ALL
  USING ("user_id" = current_app_user_id() OR pg_has_role(current_user, 'app_admin', 'member'));

CREATE POLICY fact_provenance_owner_policy ON "fact_provenance"
  FOR ALL
  USING ("user_id" = current_app_user_id() OR pg_has_role(current_user, 'app_admin', 'member'));

CREATE POLICY canonical_candidate_intelligence_owner_policy ON "canonical_candidate_intelligence"
  FOR ALL
  USING ("user_id" = current_app_user_id() OR pg_has_role(current_user, 'app_admin', 'member'));

CREATE POLICY outcome_events_owner_policy ON "outcome_events"
  FOR ALL
  USING ("user_id" = current_app_user_id() OR pg_has_role(current_user, 'app_admin', 'member'));

CREATE POLICY action_events_owner_policy ON "action_events"
  FOR ALL
  USING ("user_id" = current_app_user_id() OR pg_has_role(current_user, 'app_admin', 'member'));

CREATE POLICY predictions_owner_policy ON "predictions"
  FOR ALL
  USING ("user_id" = current_app_user_id() OR pg_has_role(current_user, 'app_admin', 'member'));

CREATE POLICY prediction_feedback_owner_policy ON "prediction_feedback"
  FOR ALL
  USING ("user_id" = current_app_user_id() OR pg_has_role(current_user, 'app_admin', 'member'));

CREATE POLICY recommendations_owner_policy ON "recommendations"
  FOR ALL
  USING ("user_id" = current_app_user_id() OR pg_has_role(current_user, 'app_admin', 'member'));

CREATE POLICY events_owner_policy ON "events"
  FOR ALL
  USING ("user_id" = current_app_user_id() OR pg_has_role(current_user, 'app_admin', 'member'));

CREATE POLICY job_applications_owner_policy ON "job_applications"
  FOR ALL
  USING ("user_id" = current_app_user_id() OR pg_has_role(current_user, 'app_admin', 'member'));

CREATE POLICY application_timeline_events_owner_policy ON "application_timeline_events"
  FOR ALL
  USING (
    EXISTS (
      SELECT 1 FROM "job_applications" ja
      WHERE ja."id" = "application_timeline_events"."application_id"
        AND ja."user_id" = current_app_user_id()
    )
    OR pg_has_role(current_user, 'app_admin', 'member')
  );

CREATE POLICY application_sources_owner_policy ON "application_sources"
  FOR ALL
  USING (
    EXISTS (
      SELECT 1 FROM "job_applications" ja
      WHERE ja."id" = "application_sources"."application_id"
        AND ja."user_id" = current_app_user_id()
    )
    OR pg_has_role(current_user, 'app_admin', 'member')
  );

CREATE POLICY application_status_history_owner_policy ON "application_status_history"
  FOR ALL
  USING (
    EXISTS (
      SELECT 1 FROM "job_applications" ja
      WHERE ja."id" = "application_status_history"."application_id"
        AND ja."user_id" = current_app_user_id()
    )
    OR pg_has_role(current_user, 'app_admin', 'member')
  );

CREATE POLICY email_messages_owner_policy ON "email_messages"
  FOR ALL
  USING (
    "user_id" = current_app_user_id()
    OR ("user_id" IS NULL AND pg_has_role(current_user, 'app_admin', 'member'))
  );

CREATE POLICY email_attachments_owner_policy ON "email_attachments"
  FOR ALL
  USING (
    EXISTS (
      SELECT 1 FROM "email_messages" em
      WHERE em."id" = "email_attachments"."email_message_id"
        AND (em."user_id" = current_app_user_id() OR em."user_id" IS NULL)
    )
    OR pg_has_role(current_user, 'app_admin', 'member')
  );

CREATE POLICY idempotency_records_service_policy ON "idempotency_records"
  FOR ALL
  USING (
    pg_has_role(current_user, 'app_admin', 'member')
    OR pg_has_role(current_user, 'app_worker', 'member')
    OR pg_has_role(current_user, 'app_runtime', 'member')
  );
